server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  profiles:
    active: prod
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    username: ${DBMS_USERNAME:root}
    password: ${$DBMS_PASSWORD:Trankhacnhu132!}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  valid-duration: 10 # second
  refreshable-duration: 120 #second